[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "souko"
description = "Souko: data exporter/loader"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dynamic = ["version"]

authors = [
    { name = "Simon Kojima" },
]

dependencies = ["numpy", "black"]

[project.optional-dependencies]
export = ["mne>=1.8"]

[tool.setuptools.dynamic]
version = { attr = "souko.__version__" }

[tool.setuptools.packages.find]
where = ["."]
include = ["souko*"]
